# deploy-azure.ps1 - Automated Azure Deployment Script for Retail Optimization Platform
# Generated by Antigravity

$ErrorActionPreference = "Stop"

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "   Azure 24/7 Deployment Script - Retail Platform" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# 1. Ensure user is logged into Azure
Write-Host "`n[1/7] Verifying Azure Authentication..." -ForegroundColor Yellow
$account = az account show --output json 2>$null
if (-not $account) {
    Write-Host "You are not logged in to Azure. Launching browser to log in..." -ForegroundColor Cyan
    az login
}
$subscription = (az account show --query name -o tsv)
Write-Host "Logged in to subscription: $subscription" -ForegroundColor Green

# 2. Configure variables
Write-Host "`n[2/7] Initializing deployment variables..." -ForegroundColor Yellow
$suffix = Get-Random -Minimum 10000 -Maximum 99999
$resourceGroup = "RetailOptRG"
$location = "centralindia"
$sqlServerName = "retail-db-server-$suffix"
$sqlDbName = "RetailOptimizationDb"
$sqlAdmin = "dbadmin"

# Generate a strong password
$chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$"
$sqlPassword = -join ((1..16) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
# Ensure it contains a mix
$sqlPassword += "A1!a"

$appServicePlan = "RetailOptimizationPlan"
$webAppName = "retail-optimization-$suffix"

Write-Host "Resource Group:    $resourceGroup"
Write-Host "Location:          $location"
Write-Host "SQL Server Name:   $sqlServerName.database.windows.net"
Write-Host "SQL Database:      $sqlDbName"
Write-Host "SQL Admin User:    $sqlAdmin"
Write-Host "SQL Admin Pass:    (Generated and saved to azure-deploy-credentials.txt)"
Write-Host "Web App Name:      $webAppName.azurewebsites.net"

# Save credentials locally
$credsContent = @"
Azure Deployment Credentials for Retail Optimization Platform
=============================================================
Date: $((Get-Date).ToString())
Resource Group:    $resourceGroup
Location:          $location
SQL Server Host:   $sqlServerName.database.windows.net
SQL Database Name: $sqlDbName
SQL Admin User:    $sqlAdmin
SQL Admin Password: $sqlPassword
Web App URL:       https://$webAppName.azurewebsites.net
"@
$credsContent | Out-File -FilePath "azure-deploy-credentials.txt" -Encoding utf8
Write-Host "Credentials saved to azure-deploy-credentials.txt" -ForegroundColor Green

# 3. Create Resources
Write-Host "`n[3/7] Creating Resource Group..." -ForegroundColor Yellow
az group create --name $resourceGroup --location $location | Out-Null

Write-Host "Creating Azure SQL Server (this may take a minute)..." -ForegroundColor Yellow
az sql server create --name $sqlServerName --resource-group $resourceGroup --location $location --admin-user $sqlAdmin --admin-password $sqlPassword | Out-Null

Write-Host "Creating SQL Database (Basic/Free tier)..." -ForegroundColor Yellow
az sql db create --resource-group $resourceGroup --server $sqlServerName --name $sqlDbName --service-objective Basic | Out-Null

Write-Host "Configuring database firewall rules..." -ForegroundColor Yellow
az sql server firewall-rule create --resource-group $resourceGroup --server $sqlServerName --name AllowAllAzureIPs --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 | Out-Null

# 4. Create App Service
Write-Host "`n[4/7] Creating App Service Plan (Free F1 Tier)..." -ForegroundColor Yellow
az appservice plan create --name $appServicePlan --resource-group $resourceGroup --location $location --sku F1 | Out-Null

Write-Host "Creating Web App (Windows, .NET 8)..." -ForegroundColor Yellow
az webapp create --name $webAppName --plan $appServicePlan --resource-group $resourceGroup --runtime "dotnet:8" | Out-Null

# 5. Configure connection string
Write-Host "`n[5/7] Configuring application connection strings..." -ForegroundColor Yellow
$connectionString = "Server=tcp:$sqlServerName.database.windows.net,1433;Database=$sqlDbName;User ID=$sqlAdmin;Password=$sqlPassword;Encrypt=true;TrustServerCertificate=false;Connection Timeout=30;"
az webapp config connection-string set --resource-group $resourceGroup --name $webAppName --connection-string-type SQLServer --settings DefaultConnection="$connectionString" | Out-Null

# 6. Publish App locally
Write-Host "`n[6/7] Compiling and publishing app locally..." -ForegroundColor Yellow
if (Test-Path ".\publish") { Remove-Item -Recurse -Force ".\publish" }
if (Test-Path ".\publish.zip") { Remove-Item -Force ".\publish.zip" }

dotnet publish .\RetailOptimizationPlatform.Web\RetailOptimizationPlatform.Web.csproj -c Release -o .\publish

Write-Host "Compressing publish package..." -ForegroundColor Yellow
Compress-Archive -Path .\publish\* -DestinationPath .\publish.zip -Force

# 7. Deploy to Azure
Write-Host "`n[7/7] Deploying package to Azure App Service (this may take a couple of minutes)..." -ForegroundColor Yellow
az webapp deploy --resource-group $resourceGroup --name $webAppName --src-path .\publish.zip

# Clean up local zip and publish folders
Remove-Item -Recurse -Force ".\publish"
Remove-Item -Force ".\publish.zip"

Write-Host "`n==================================================" -ForegroundColor Green
Write-Host "   DEPLOYMENT COMPLETED SUCCESSFULLY!" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host "Your live website URL is: https://$webAppName.azurewebsites.net" -ForegroundColor Green
Write-Host "A record of credentials has been saved to: azure-deploy-credentials.txt" -ForegroundColor Green
Write-Host "Note: Database migrations and trigger/SP configuration will execute automatically on first page load." -ForegroundColor Yellow
Write-Host "==================================================" -ForegroundColor Green
