// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailOptimizationPlatform.Data;

#nullable disable

namespace RetailOptimizationPlatform.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604175935_ConfigureOrderTrigger")]
    partial class ConfigureOrderTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_Price", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Inventory_StockQuantity", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Wireless Mouse",
                            Price = 25.99m,
                            Sku = "MOUSE-001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "Mechanical Keyboard",
                            Price = 89.50m,
                            Sku = "KEY-002",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "USB-C Monitor",
                            Price = 299.99m,
                            Sku = "MON-003",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            ItemName = "Ergonomic Chair",
                            Price = 150.00m,
                            Sku = "FURN-004",
                            StockQuantity = 5
                        });
                });

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasTrigger("trg_AutoDecrementStock");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "John Doe",
                            InventoryId = 1,
                            OrderDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 51.98m
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Jane Smith",
                            InventoryId = 2,
                            OrderDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 89.50m
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Bob Johnson",
                            InventoryId = 3,
                            OrderDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 299.99m
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Alice Brown",
                            InventoryId = 4,
                            OrderDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 150.00m
                        });
                });

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Newark",
                            ContactPerson = "Markus Senn",
                            Country = "USA",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 50000m,
                            Email = "markus@logitech.com",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeadTimeDays = 5,
                            Name = "Logitech Corp",
                            PaymentTerms = "Net 30",
                            PhoneNumber = "+1-555-0199",
                            Rating = 4.8m,
                            State = "NJ"
                        },
                        new
                        {
                            Id = 2,
                            City = "Hong Kong",
                            ContactPerson = "Nick Chen",
                            Country = "Hong Kong",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 30000m,
                            Email = "nick@keychron.com",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeadTimeDays = 12,
                            Name = "Keychron Inc",
                            PaymentTerms = "Net 15",
                            PhoneNumber = "+852-2345-6789",
                            Rating = 4.5m,
                            State = ""
                        },
                        new
                        {
                            Id = 3,
                            City = "Round Rock",
                            ContactPerson = "Sarah Connor",
                            Country = "USA",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 100000m,
                            Email = "sarah@dell.com",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeadTimeDays = 7,
                            Name = "Dell Technologies",
                            PaymentTerms = "Net 45",
                            PhoneNumber = "+1-800-456-3355",
                            Rating = 4.7m,
                            State = "TX"
                        });
                });

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Order", b =>
                {
                    b.HasOne("RetailOptimizationPlatform.Core.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
