// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailOptimizationPlatform.Data;

#nullable disable

namespace RetailOptimizationPlatform.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604080609_UpdateDatabaseArchitecture")]
    partial class UpdateDatabaseArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_Price", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Inventory_StockQuantity", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Wireless Mouse",
                            Price = 25.99m,
                            Sku = "MOUSE-001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "Mechanical Keyboard",
                            Price = 89.50m,
                            Sku = "KEY-002",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "USB-C Monitor",
                            Price = 299.99m,
                            Sku = "MON-003",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            ItemName = "Ergonomic Chair",
                            Price = 150.00m,
                            Sku = "FURN-004",
                            StockQuantity = 5
                        });
                });

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RetailOptimizationPlatform.Core.Entities.Order", b =>
                {
                    b.HasOne("RetailOptimizationPlatform.Core.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
